all: clean prep compile run

clean:
	rm -rf dist
prep:
	mkdir dist
compile: task1.9main.bin task2.1main.bin task2.4main.bin task3.1main.bin task3.2main.bin task3.3main.bin task3.4main.bin task3.5main.bin task3.6main.bin

task1.9main.bin:
	gcc -g src/task1.9.c  -o dist/task1.9main.bin

task2.1main.bin:
	gcc -g src/task2.1.c  -o dist/task2.1main.bin


task2.4main.bin:
	gcc  -g src/task2.4.c -o dist/task2.4main.bin
	
task3.1main.bin:
	gcc  -g src/task3.1.c  -o dist/task3.1main.bin


task3.2main.bin:
	gcc  -g src/task3.2.c  -o dist/task3.2main.bin
	
	
task3.3main.bin: 
	gcc  -g src/task3.3.c  -o dist/task3.3main.bin

task3.4main.bin: 
	gcc  -g src/task3.4.c  -o dist/task3.4main.bin

task3.5main.bin: 
	gcc  -g src/task3.5.c  -o dist/task3.5main.bin
	
task3.6main.bin:
	gcc  -g src/task3.6.c  -o dist/task3.6main.bin
	
	

